import React from 'react';
const IMG = {
  QRCODE: require('./Img/qr-code.png'),
  APPSTORE: require('./Img/app-store.png'),
  GOOGLE: require('./Img/gg-play.png'),
  GALLERY: require('./Img/app-gallery.png'),
  PAY1: require('./Img/pay1.PNG'),
  PAY2: require('./Img/pay2.PNG'),
  PAY3: require('./Img/pay3.PNG'),
  PAY4: require('./Img/pay4.PNG'),
  PAY5: require('./Img/pay5.PNG'),
  SHIP1: require('./Img/ship1.PNG'),
  SHIP2: require('./Img/ship2.PNG'),
  SHIP3: require('./Img/ship3.PNG'),
  SHIP4: require('./Img/ship4.PNG'),
  SHIP5: require('./Img/ship5.PNG'),
  SHIP6: require('./Img/ship6.PNG'),
  SHIP7: require('./Img/ship7.PNG'),
  SHIP8: require('./Img/ship7.PNG'),
  SHIP9: require('./Img/ship8.PNG'),
  BANNER_IMG: require('./Img/banner.png'),
  EMPTY_COMMENT: require('./Img/rating.png'),
  USER_IMG: require('./Img/User.jpg'),
  EMPTY_ORDER_IMG: './Img/empty_order.png',
  SALE: require('./Img/sale.jpg'),
  LOGO2: require('./Img/logo-2.png'),
  LOGO: require('./Img/shopee.png'),
  PAY: require('./Img/pay.png'),
  NO_CART: require('./Img/no-cart.png'),
  SEARCH_IMG: require('./Img/Search.png'),
  EMPTY_CART: require('./Img/empty-cart.png'),
  FLASH_SALE: require('./Img/flash_sale.jpg'),
  SALES_XU: require('./Img/sales_xu.jpg'),
  PAGE_NOT_FOUND_IMG: require('./Img/Pagenotfound.jpg'),
  SALE_STICKER: require('./Img/sale_sticker.png'),
};
export default IMG;
